### ISSUE TITLE
Custom Middleware add/remove headers

### ISSUE THREAD

**Issue by MrSent** [RickStrahl/Westwind.AspNetCore#13]
I was looking into ways of adding and removing headers from my ASP.NET Core application. It's an API so there is no UI to it. After looking around I worked out that using the middleware technique to add and remove headers is probably the best as I need to include information in every response. I used the techniques in the CustomMiddleware.cs class and added code to the Startup.Configure method. Adding headers seems to work so for example:

opt.HeadersToAdd.Add("X-API-Version", sVersionString);
opt.HeadersToAdd.Add("X-ClientCommand", sCommandToExecute);

However, removing doesn't remove the headers. Any thoughts? It's not overly important to remove these, but I like to remove somethings just to make the response cleaner.

opt.HeadersToRemove.Add("X-Powered-By");
opt.HeadersToRemove.Add("x-aspnet-version");
opt.HeadersToRemove.Add("Server");

**Comment by RickStrahl** [comment]
As mentioned in the docs, header removal may depend on placement in the pipeline. If you remove headers you need to do it after the headers were added already but before the server has sent them.

Also some headers come from the base WebServer. I think the X-Powered-By come from IIS and you may not be able to remove those from within the ASP.NET Core code. For IIS headers you can use web.config and as described in [the support post](https://weblog.west-wind.com/posts/2022/Jul/07/Back-to-Basics-Custom-HTTP-Response-Header-Manipulation-in-ASPNET-Core#web-server-global-headers).
