### ISSUE TITLE
Add licence

### ISSUE THREAD

**Issue by kondelik** [RickStrahl/Westwind.AspNetCore#2]
Please, add some licence.

I dont know what can i do with your helpers (and i reaaaaly want to dig in your MarkdawnTagHelper 😍 )

**Comment by kondelik** [comment]
Oh, I wanted to create this "issue" to [Westwind.Web.MarkdownControl](https://github.com/RickStrahl/Westwind.Web.MarkdownControl) - sorry, but even [Westwind.Web.MarkdownControl](https://github.com/RickStrahl/Westwind.Web.MarkdownControl) is not licensed.

**Comment by RickStrahl** [comment]
License is MIT. Adding...
