### ISSUE TITLE
Issue with XSS

### ISSUE THREAD

**Issue by ashleybroughton** [RickStrahl/Westwind.AspNetCore#4]
Hi, we're using your library over at https://github.com/csharpfritz/CoreWiki/issues/144 to render wiki content and comments, but we appear to be having an issue with XSS.

Is this something that can be fixed in the library, or something we have to update on our end when using the `<markdown>` tag?

**How we're using the library:**

https://github.com/csharpfritz/CoreWiki/blob/dev/CoreWiki/Pages/Components/ListComments/ListComments.cshtml#L41

https://github.com/csharpfritz/CoreWiki/blob/dev/CoreWiki/Pages/Details.cshtml#L19

**Comment log of issue:**

https://github.com/csharpfritz/CoreWiki/issues/144

**Comment by RickStrahl** [comment]
There's no built-in XSS support in the markdown parser. You have to treat the HTML coming as you would any free form HTML in your application.

You can however disable raw HTML support which removes the easiest targets (script tags):
```cs
services.AddMarkdown(config =>
{
    // Create custom MarkdigPipeline 
    // using MarkDig; for extension methods
    config.ConfigureMarkdigPipeline = builder =>
    {
        builder.UseEmphasisExtras(Markdig.Extensions.EmphasisExtras.EmphasisExtraOptions.Default)
            .UsePipeTables()
            .UseGridTables()                        
            .UseAutoIdentifiers(AutoIdentifierOptions.GitHub) // Headers get id="name" 
            .UseAutoLinks() // URLs are parsed into anchors
            .UseAbbreviations()
            .UseYamlFrontMatter()
            .UseEmojiAndSmiley(true)                        
            .UseListExtras()
            .UseFigures()
            .UseTaskLists()
            .UseCustomContainers()
            .UseGenericAttributes()
            .DisableHtml();
    };
});
```

Specifically the `.DisableHtml()` below which disallows HTML content.

You probably also need to  add a simple handler to remove `javascript:` from HTML output which allows links to include javascript tags that can excecute on click.

```cs
markdown = markdown.Replace("javascript:","");
```

If you leave HTML tags in you can also create some rudimentary scrubbing. I have this in Markdown Monster's processing pipeline (one of the custom post processors) when script support is disabled:

```
        /// <summary>
        /// Parses out script tags that might not be encoded yet
        /// </summary>
        /// <param name="html"></param>
        /// <returns></returns>
        protected string ParseScript(string html)
        {
            html = html.Replace("<script", "&lt;script");
            html = html.Replace("</script", "&lt;/script");
            html = html.Replace("javascript:", "javaScript:");
            return html;
        }
```

This is far from perfect, but it prevents the most obvious attacks.

**Comment by ashleybroughton** [comment]
Hi Rick,

I don't think the javascript: tag is case sensitive. JaVaScriPT:alert('hi'), would still execute (at least that's the case in chrome).

**Comment by RickStrahl** [comment]
Ok, then just remove it or put something else in place that doesn't work.

```cs
html = html.Replace("javascript:", "unsupported:");
```

**Comment by RickStrahl** [comment]
Added a number of more comprehensive mitigations for cross site scripting.

* [Blog post: Markdown and Cross Site Scripting](https://weblog.west-wind.com/posts/2018/Aug/31/Markdown-and-Cross-Site-Scripting)
* [Library XSS Documentation](https://github.com/RickStrahl/Westwind.AspNetCore/tree/master/Westwind.AspNetCore.Markdown#westwindaspnetcore-and-xss)
