### ISSUE TITLE
Change markdown renderer used

### ISSUE THREAD

**Issue by fracek** [RickStrahl/Westwind.AspNetCore#5]
For a project I need to be able to generate [AMP](https://www.ampproject.org/) as well as "normal" HTML pages. I'm using your library at the moment, works great thanks!

I was wondering if there is any way to change the renderer used by `Markdown.ParseHtmlString` to a custom one so that I can generate AMP-specific html?

**Comment by RickStrahl** [comment]
moving remaining issues to `Westwind.AspNetCore.Markdown` Repository.

**Comment by RickStrahl** [comment]
This is now possible using this mechanism:
https://github.com/RickStrahl/Westwind.AspNetCore.Markdown#using-a-different-markdown-parser
